<a href="https://colab.research.google.com/github/u-dharshini/MachineLearning/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# -----------------------------------
# Step 1: Collect data from user
# 5 students, 4 subjects (or attributes)
# -----------------------------------
data = []

print("Enter marks for 5 students in 4 subjects (space-separated):")
for i in range(5):
    row = list(map(float, input(f"Student {i+1}: ").split()))
    if len(row) != 4:
        print("Error: Enter exactly 4 numbers")
        exit()
    data.append(row)

data = np.array(data)

print("\nSTEP 1: ORIGINAL DATASET")
print(data)

# -----------------------------------
# Step 2: Compute mean
# -----------------------------------
mean = np.mean(data, axis=0)
print("\nSTEP 2: MEAN OF EACH ATTRIBUTE")
print(mean)

# -----------------------------------
# Step 3: Mean-center the data
# -----------------------------------
centered_data = data - mean
print("\nSTEP 3: MEAN-CENTERED DATA")
print(centered_data)

# -----------------------------------
# Step 4: Covariance matrix
# -----------------------------------
cov_matrix = np.cov(centered_data.T)  # columns = variables
print("\nSTEP 4: COVARIANCE MATRIX")
print(cov_matrix)

# -----------------------------------
# Step 5: Eigenvalues and Eigenvectors
# -----------------------------------
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print("\nSTEP 5: EIGENVALUES")
print(eigenvalues)
print("\nSTEP 5: EIGENVECTORS")
print(eigenvectors)

# -----------------------------------
# Step 6: Explained Variance (%)
# -----------------------------------
total_variance = np.sum(eigenvalues)
explained_variance = (eigenvalues / total_variance) * 100
print("\nSTEP 6: EXPLAINED VARIANCE (%)")
print(explained_variance)

# -----------------------------------
# Step 7: Minimum components to retain >=90% variance
# -----------------------------------
sorted_index = np.argsort(eigenvalues)[::-1]  # descending
sorted_variance = explained_variance[sorted_index]
cumulative_variance = np.cumsum(sorted_variance)
num_components = np.where(cumulative_variance >= 90)[0][0] + 1

print("\nMINIMUM NUMBER OF COMPONENTS REQUIRED")
print(num_components)

# -----------------------------------
# Step 8: Project data onto top principal components
# -----------------------------------
selected_vectors = eigenvectors[:, sorted_index[:num_components]]
reduced_data = centered_data.dot(selected_vectors)

print("\nSTEP 8: REDUCED DATASET")
print(reduced_data)

print("\nTOTAL VARIANCE RETAINED (%)")
print(cumulative_variance[num_components - 1])

Enter marks for 5 students in 4 subjects (space-separated):
Student 1: 70 65 80 75
Student 2: 60 58 75 68 
Student 3: 78 72 85 80
Student 4: 55 50 70 60
Student 5: 85 80 90 88

STEP 1: ORIGINAL DATASET
[[70. 65. 80. 75.]
 [60. 58. 75. 68.]
 [78. 72. 85. 80.]
 [55. 50. 70. 60.]
 [85. 80. 90. 88.]]

STEP 2: MEAN OF EACH ATTRIBUTE
[69.6 65.  80.  74.2]

STEP 3: MEAN-CENTERED DATA
[[  0.4   0.    0.    0.8]
 [ -9.6  -7.   -5.   -6.2]
 [  8.4   7.    5.    5.8]
 [-14.6 -15.  -10.  -14.2]
 [ 15.4  15.   10.   13.8]]

STEP 4: COVARIANCE MATRIX
[[153.3 144.   97.5 132.1]
 [144.  137.   92.5 126. ]
 [ 97.5  92.5  62.5  85. ]
 [132.1 126.   85.  116.2]]

STEP 5: EIGENVALUES
[4.67307144e+02 1.55383080e+00 1.35857042e-01 3.16782894e-03]

STEP 5: EIGENVECTORS
[[ 0.57097016  0.78077814 -0.23284433 -0.10080717]
 [ 0.54109538 -0.29359751  0.57544712 -0.53840217]
 [ 0.36563055 -0.03589008  0.41612339  0.83178574]
 [ 0.497517   -0.55036161 -0.66444371  0.08996383]]

STEP 6: EXPLAINED VARIANCE (%)
[9.963